openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://laravelapi.test'
paths:
  /api/list/categories:
    get:
      summary: 'Get all categories'
      operationId: getAllCategories
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      name: 'update category from api'
                    -
                      id: 2
                      name: 'sed id culpa'
                    -
                      id: 3
                      name: 'quia quia nihil'
                    -
                      id: 4
                      name: 'omnis sed illum'
                    -
                      id: 5
                      name: 'quia explicabo hic'
                    -
                      id: 6
                      name: 'inventore est velit'
                    -
                      id: 7
                      name: 'laboriosam voluptas animi'
                    -
                      id: 8
                      name: 'in rem qui'
                    -
                      id: 9
                      name: 'repellat amet possimus'
                    -
                      id: 10
                      name: 'dolorum quis perferendis'
                    -
                      id: 11
                      name: 'New category from API'
                    -
                      id: 12
                      name: 'New category from API'
                    -
                      id: 13
                      name: 'New category from API'
                    -
                      id: 15
                      name: 'Categoria con fichero 3'
                    -
                      id: 16
                      name: 'Categoria con fichero 1'
                    -
                      id: 17
                      name: 'Categoria con fichero 1'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: 'update category from api'
                      -
                        id: 2
                        name: 'sed id culpa'
                      -
                        id: 3
                        name: 'quia quia nihil'
                      -
                        id: 4
                        name: 'omnis sed illum'
                      -
                        id: 5
                        name: 'quia explicabo hic'
                      -
                        id: 6
                        name: 'inventore est velit'
                      -
                        id: 7
                        name: 'laboriosam voluptas animi'
                      -
                        id: 8
                        name: 'in rem qui'
                      -
                        id: 9
                        name: 'repellat amet possimus'
                      -
                        id: 10
                        name: 'dolorum quis perferendis'
                      -
                        id: 11
                        name: 'New category from API'
                      -
                        id: 12
                        name: 'New category from API'
                      -
                        id: 13
                        name: 'New category from API'
                      -
                        id: 15
                        name: 'Categoria con fichero 3'
                      -
                        id: 16
                        name: 'Categoria con fichero 1'
                      -
                        id: 17
                        name: 'Categoria con fichero 1'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: 'update category from api'
      tags:
        - Categories
  /api/categories:
    get:
      summary: 'Get all categories'
      operationId: getAllCategories
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Categories
    post:
      summary: 'Create a category'
      operationId: createACategory
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: facere
                  nullable: false
              required:
                - name
  '/api/categories/{id}':
    get:
      summary: 'Show category'
      operationId: showCategory
      description: 'Get a category by ID'
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Categories
    put:
      summary: 'Update a category'
      operationId: updateACategory
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: similique
                  nullable: false
              required:
                - name
    delete:
      summary: 'Delete a category'
      operationId: deleteACategory
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Categories
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the category.'
        example: 1
        required: true
        schema:
          type: integer
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
  /api/products:
    get:
      summary: ''
      operationId: getApiProducts
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Products
tags:
  -
    name: Categories
    description: 'Manage categories'
  -
    name: Endpoints
    description: ''
  -
    name: Products
    description: "\n Managing products"
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
